CREATE TABLE CTX_USER (
	VERSION  INTEGER DEFAULT 0,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    USERTYPE VARCHAR(10) NOT NULL,
    ENABLED VARCHAR(1) DEFAULT '1',
    FAILED_COUNT INTEGER DEFAULT 0);
    
    
ALTER TABLE CTX_USER ADD PRIMARY KEY (USERNAME);
