CREATE TABLE CTX_GUARDIAN (
    RECID  INTEGER NOT NULL AUTO_INCREMENT,
	VERSION  INTEGER DEFAULT 0,
    LAST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    FIRST_NAME VARCHAR(50) NOT NULL,
    NAME_SUFFIX VARCHAR(35) NOT NULL,
    BDATE DATE,
    ADDRESS1 VARCHAR(50), 
    ADDRESS2 VARCHAR(50), 
    ADDRESS3 VARCHAR(50),
    CONTACT_NO VARCHAR(20),
    PRIMARY KEY (RECID));

CREATE INDEX IDX_GUARDIAN_NAMES ON CTX_STUDENT(LAST_NAME, FIRST_NAME);
    
