CREATE TABLE CTX_STU_GUA_REL (
    RECID  INTEGER NOT NULL AUTO_INCREMENT,
    VERSION  INTEGER DEFAULT 0,
    ST_RECID INTEGER NOT NULL,
    GU_RECID INTEGER NOT NULL,
    TYPE VARCHAR(5) NOT NULL,
    PRIMARY KEY (RECID)
);

ALTER TABLE CTX_STU_GUA_REL ADD CONSTRAINT UK_STUD_PG_ID UNIQUE (ST_RECID, GU_RECID);
ALTER TABLE CTX_STU_GUA_REL ADD CONSTRAINT FK_STUD_ID FOREIGN KEY (ST_RECID) REFERENCES CTX_STUDENT(RECID);
ALTER TABLE CTX_STU_GUA_REL ADD CONSTRAINT FK_PG_ID FOREIGN KEY (GU_RECID) REFERENCES CTX_GUARDIAN(RECID);


